use_frameworks!

platform :ios, '10.0'

target 'ZLImageEditorSiyaq_Example' do
  pod 'ZLImageEditorSiyaq', :path => '../'

  target 'ZLImageEditorSiyaq_Tests' do
    inherit! :search_paths

    
  end
end
